language: cpp

compiler: 
    - gcc
    - clang  

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    # clang 3.5
    - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list
    - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" | sudo tee -a /etc/apt/sources.list
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -

    - sudo apt-get update -qq

install:
    - if [ "$CXX" == "clang++" ]; then sudo apt-get remove -qq clang-3.4; fi
    - whereis clang
    - which clang
    - whereis clang++
    - which clang++
    - if [ "$CXX" == "clang++" ]; then sudo apt-get install -qq clang-3.5; fi
    - if [ "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.5 35 --slave /usr/bin/clang++ clang++ /usr/bin/clang++-3.5; fi
    - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.9; fi
    - if [ "$CXX" == "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
    - $CXX -v

script: "./run-tests.sh"
